In [1]:
import seaborn as sns
import metapack as mp
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from IPython.display import display 

%matplotlib inline
sns.set_context('notebook')
mp.jupyter.init()

In [2]:
pkg = mp.jupyter.open_package()
#pkg = mp.jupyter.open_source_package()
pkg

# Distressed Housing Tracts 2013-2021
`ffiec.gov-census-tract-1.6.4` Last Update: 2022-10-30T15:35:53

_An extract of a subset of columns from the FFIEC Census Flat File, including flags that indicate a tract is distressed._


This dataset extracts the columns for distressed tracts from the FFIEC compilation of census data, for use in their FFIEC Census Windows Application. It includes only 25 columns, the first 17 columns of the file, which have geographic identifiers, median income, and three population totals. The reamaining 8 columns hold flags to indicate if a tract is distressed.

* 1205	Identifies Income Level Indicator
* 1206	Meets current year's poverty CRA distressed criterion?
* 1207	Meets current year's unemployment CRA distressed criterion?
* 1208	Meets current year's population CRA distressed criterion?
* 1209	Meets current year's remote rural (low density) CRA underserved criterion?
* 1210	Meets at least one of the previous year's CRA distressed criteria?
* 1211	Meets previous year's CRA underserved criterion?
* 1212	Meets at least one of current or previous year's CRA distressed/underserved tract criteria?


## Caveats

The 2017 file, as distributed by FFIEC, is broken: it includes a ZIP file with in the ZIP file, which Metapack cannot read. This file has been manually extracted and stored in the source package.
## Documentation Links

* [File information](doc/cen2018.pdf) Description of the 2018 census file, including all columns. Other years are similar
* [homepage](https://www.ffiec.gov/censusapp.htm)



## Contacts

* **Wrangler** [Eric Busboom](mailto:eric@civicknowledge.com), [Civic Knowledge](http://civicknowledge.com)

## Resources

* ** [ffiec_distressed](data/ffiec_distressed.csv)**. Distressed tracts

## References
<ul><li> <strong><a href="https://www.ffiec.gov/Census/Census_Flat_Files/Census2013.zip#*.csv">ffiec_census_2013</a></strong>. 2013 Census Flat File</li><li> <strong><a href="https://www.ffiec.gov/Census/Census_Flat_Files/CENSUS2014.ZIP#*.csv">ffiec_census_2014</a></strong>. 2014 Census Flat File</li><li> <strong><a href="https://www.ffiec.gov/Census/Census_Flat_Files/CENSUS2015.zip#*.csv">ffiec_census_2015</a></strong>. 2015 Census Flat File</li><li> <strong><a href="https://www.ffiec.gov/Census/Census_Flat_Files/CENSUS2016.zip#*.csv">ffiec_census_2016</a></strong>. 2016 Census Flat File</li><li> <strong>ffiec_census_2017</string>, <em>data/Census2017.zip#*.csv</em>. 2017 Census Flat File</li><li> <strong><a href="https://www.ffiec.gov/Census/Census_Flat_Files/CENSUS2018.zip#*.csv">ffiec_census_2018</a></strong>. 2018 Census Flat File</li><li> <strong><a href="https://www.ffiec.gov/Census/Census_Flat_Files/CENSUS2019.zip#*.csv">ffiec_census_2019</a></strong>. 2019 Census Flat File</li><li> <strong><a href="https://www.ffiec.gov/Census/Census_Flat_Files/CENSUS2020.zip#*.csv">ffiec_census_2020</a></strong>. 2020 Census Flat File</li><li> <strong><a href="https://www.ffiec.gov/Census/Census_Flat_Files/CENSUS2021.zip#*.csv">ffiec_census_2021</a></strong>. 2021 Census Flat File</li><li> <strong><a href="https://www.ffiec.gov/Census/Census_Flat_Files/CensusFlatFile2022.zip#*.csv">ffiec_census_2022</a></strong>. 2022 Census Flat File</li><ul>

In [7]:
df = pkg.resource('ffiec_distressed').dataframe()
df.year.value_counts()

2022    87275
2017    75883
2018    75883
2021    75883
2019    75882
2020    75882
2013    75881
2014    75881
2015    75880
2016    75880
Name: year, dtype: Int64

In [18]:
# 2022 has a lot of new tracts, about 11,400 more
g22 = set(df[df.year == 2022].geoid)
g21 = set(df[df.year == 2021].geoid)

print(len(g22), len(g21))

new_tracts = list(g22 - g21)

df[df.geoid.isin(new_tracts)].sample(20)

87275 75883

,geoid,year,msa_md_code,state,county,tract,principal_city_flag,small_county_flag,split_tract_flag,demo_flag,...,nonwhite,minority_percent,income_level,poverty_distressed,unemployment_distressed,population_distressed,rural_underserved,last_year_distressed,last_year_underserved,current_prior_distressed
766241,14000US53061041813,2022,42644,53,61,41813,1,T,N,D,...,<NA>,<NA>,16,29,106,17,0,0,0,273700
723121,14000US26121003702,2022,34740,26,121,3702,0,T,N,D,...,<NA>,<NA>,17,0,0,5,5,0,0,131900
727455,14000US29071800704,2022,41180,29,71,800704,0,T,N,D,...,<NA>,<NA>,0,0,0,22,0,0,0,89700
707699,14000US15007040105,2022,99999,15,7,40105,0,T,N,D,...,<NA>,<NA>,25,149,317,153,174,55,113,743300
717065,14000US22051020304,2022,35380,22,51,20304,1,T,N,D,...,<NA>,<NA>,551,138,29,58,0,0,13,310500
720186,14000US25009211201,2022,15764,25,9,211201,0,T,N,D,...,<NA>,<NA>,263,215,88,0,0,0,0,389000
754150,14000US47155080803,2022,99999,47,155,80803,0,T,N,D,...,<NA>,<NA>,187,66,197,18,30,0,0,229300
726904,14000US28123020301,2022,99999,28,123,20301,0,S,N,D,...,<NA>,<NA>,33,0,40,0,0,0,0,92500
703723,14000US12105012701,2022,29460,12,105,12701,0,T,N,D,...,<NA>,<NA>,9,126,40,0,0,0,0,235100
718377,14000US23031025204,2022,38860,23,31,25204,0,T,N,D,...,<NA>,<NA>,20,0,15,0,0,0,0,191200
704433,14000US13009970301,2022,99999,13,9,970301,0,T,N,D,...,<NA>,<NA>,86,49,11,0,0,0,0,165400
716938,14000US22033003913,2022,12940,22,33,3913,1,T,N,D,...,<NA>,<NA>,111,0,0,0,0,0,0,246200
738849,14000US36115080302,2022,24020,36,115,80302,0,T,N,D,...,<NA>,<NA>,120,0,13,0,0,0,0,195500
745650,14000US40051000702,2022,36420,40,51,702,0,T,N,D,...,<NA>,<NA>,56,13,15,0,1,5,0,85100
700857,14000US12057011715,2022,45300,12,57,11715,0,T,N,D,...,<NA>,<NA>,0,0,0,0,0,0,0,149000
697923,14000US09001022101,2022,14860,9,1,22101,1,T,N,D,...,<NA>,<NA>,118,16,66,35,0,0,0,357200
752397,14000US45079011306,2022,17900,45,79,11306,1,T,N,D,...,<NA>,<NA>,149,24,98,42,21,0,30,248700
748723,14000US42037051102,2022,14100,42,37,51102,1,T,N,D,...,<NA>,<NA>,6,0,0,4,0,0,0,115400
753993,14000US47137925101,2022,99999,47,137,925101,0,S,N,D,...,<NA>,<NA>,69,0,0,0,0,0,63,168900
756639,14000US48113020800,2022,19124,48,113,20800,1,T,N,D,...,<NA>,<NA>,26,0,21,0,0,0,6,78000

In [22]:
from rowgenerators import geoframe
t20 = geoframe('censusgeo://US/140')

AssertionError: (2018, 'TRACT')

In [4]:
df21.iloc[:, 1204]

0        3
1        3
2        3
3        4
4        3
        ..
75877    3
75878    2
75879    2
75880    2
75881    0
Name: 4.19, Length: 75882, dtype: int64

In [5]:
df18 = pkg.reference('ffiec_census_2018').dataframe()
df18.iloc[:, 1204]

0        3
1        3
2        3
3        4
4        3
        ..
75877    3
75878    2
75879    2
75880    2
75881    0
Name: 4.19, Length: 75882, dtype: int64

In [6]:
df18

,2018,33860,01,001,020100,0,T,N,D,M,...,0.546,0.547,0.548,0.549,0.550,0.551,0.552,0.553,0.554,0.555
0,2018,33860,1,1,20200,0,T,N,D,U,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.0
1,2018,33860,1,1,20300,0,T,N,D,U,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2018,33860,1,1,20400,0,T,N,D,U,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2018,33860,1,1,20500,0,T,N,D,M,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0,0.0
4,2018,33860,1,1,20600,0,T,N,D,M,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75877,2018,99999,78,30,960900,0,I,N,I,I,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75878,2018,99999,78,30,961000,0,I,N,I,I,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75879,2018,99999,78,30,961100,0,I,N,I,I,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75880,2018,99999,78,30,961200,0,I,N,I,I,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75881,2018,99999,78,30,990000,0,I,N,I,I,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN